In [1]:
import pandas as pd
import numpy as np
import time

In [2]:
pd.options.display.max_columns=1000

In [3]:
df_djix = pd.read_csv('C:/Users/marki/Desktop/SB Data Science BC/Springboard/Capstone3-Stock_Price_Prediction/csvs/djix.csv')
df_djix['Date'] = pd.to_datetime(df_djix['Date'])
df_djix = df_djix.set_index('Date')
df_djix = df_djix.rename(columns={'Open':'djix_Open', 'High':'djix_High', 'Low':'djix_Low', 'Close':'djix_Close', 'Volume':'djix_Volume'})
df_djix['djix_prev_close'] = df_djix['djix_Close'].shift(1)
df_djix['djix_next_close'] = df_djix['djix_Close'].shift(-1)
df_djix['djix_diff'] = df_djix['djix_Close'].diff()
df_djix['djix_%change'] = df_djix['djix_Close'].pct_change()
df_djix['djix_5day_avg_close'] = df_djix['djix_Close'].rolling(5).mean()
df_djix['djix_5day_avg_diff'] = df_djix['djix_diff'].rolling(5).mean()
df_djix['djix_10day_avg_close'] = df_djix['djix_Close'].rolling(10).mean()
df_djix['djix_10day_avg_diff'] = df_djix['djix_diff'].rolling(10).mean()

In [4]:
df = df_djix
df

,djix_Open,djix_High,djix_Low,djix_Close,djix_Volume,djix_prev_close,djix_next_close,djix_diff,djix_%change,djix_5day_avg_close,djix_5day_avg_diff,djix_10day_avg_close,djix_10day_avg_diff
Date,,,,,,,,,,,,,
1896-05-27,29.39,29.39,29.39,29.39,NaN,NaN,29.11,NaN,NaN,NaN,NaN,NaN,NaN
1896-05-28,29.11,29.11,29.11,29.11,NaN,29.39,29.43,-0.28,-0.009527,NaN,NaN,NaN,NaN
1896-05-29,29.43,29.43,29.43,29.43,NaN,29.11,29.40,0.32,0.010993,NaN,NaN,NaN,NaN
1896-06-01,29.40,29.40,29.40,29.40,NaN,29.43,29.00,-0.03,-0.001019,NaN,NaN,NaN,NaN
1896-06-02,29.00,29.00,29.00,29.00,NaN,29.40,28.80,-0.40,-0.013605,29.266,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-18,32468.67,32468.67,31393.95,31490.07,508465869.0,32654.59,31253.13,-1164.52,-0.035662,32059.008,-68.808,32243.293,-257.099
2022-05-19,31262.62,31569.13,31016.41,31253.13,554268268.0,31490.07,31261.90,-236.94,-0.007524,31963.574,-95.434,32068.809,-174.484
2022-05-20,31426.94,31515.78,30635.76,31261.90,551025623.0,31253.13,31880.24,8.77,0.000281,31776.622,-186.952,31905.062,-163.747
2022-05-23,31395.89,31968.42,31395.89,31880.24,452693827.0,31261.90,31928.62,618.34,0.019779,31707.986,-68.636,31868.516,-36.546
2022-05-24,31717.61,32014.86,31365.59,31928.62,428081450.0,31880.24,NaN,48.38,0.001518,31562.792,-145.194,31845.304,-23.212

In [5]:
df.to_csv('C:/Users/marki/Desktop/SB Data Science BC/Springboard/Capstone3-Stock_Price_Prediction/csvs/df_dow.csv', index=True)